### ISSUE TITLE
show tables doesn't display all the tables

### ISSUE THREAD

**Issue by tanguyvda** [alemonteiro/brackets-sql-connector#3]
Hi,

The title says it all, if I do a show tables; it won't display every tables

 [node-log 4:31:02 PM] { Tables_in_centreon_storage: 'statistics' }
NodeDebugUtils.js:117 [node-log 4:31:02 PM] 
NodeDebugUtils.js:117 [node-log 4:31:02 PM] <-- EofPacket
NodeDebugUtils.js:117 [node-log 4:31:02 PM] { fieldCount: 254,
  warningCount: 0,
  serverStatus: 34,
  protocol41: true }
NodeDebugUtils.js:117 [node-log 4:31:02 PM] 

or the last table of the centreon_storage database is called ws_token.

It could have been a problem with the number of row displayed but no, when i do a query that gives me hundreds of line, i can scroll from the start to the end without losing any data.

**Comment by alemonteiro** [comment]
What engine are you using? MySQL?
And this occurs on the browser panel or when you run a 'show tables;' query on the editor?

On the browser panel, MySQL was showing views as tables also, I fixed this a couple of versions ago so views were only to display on the Views folder.

The MySQL query for showing tables used is: 
`SHOW FULL TABLES IN <db_name> WHERE TABLE_TYPE = 'BASE TABLE';`

Can you run this on the editor to compare the results?

**Comment by tanguyvda** [comment]
.... Sorry for the inconvenience,I've found that I must have done something wrong (connection was set up for a db called centreon_storage) and even using `use centreon`  and then typing `show tables` it was still showing the tables from centreon_storage db. But since this morning all is working as intended I think I've done a mistake while using your plugin yesterday. .

**Comment by alemonteiro** [comment]
No problem mate =)

Just remeber, the editor will always execute on the connection shown on the bottom pane. 

I'm thinking of a way to make it even clearer, because some times I also execute on the wrong db =x

Any suggestions?

**Comment by tanguyvda** [comment]
I think, it could be good to have on the bottom pane a cell with this information :+1: 

current database : db_name

**Comment by alemonteiro** [comment]
This next version should resolve it.
After executing something that changes the indicator server name, it will come back after 10 seconds.
Also added in which server each result set was executed upon and the current server on the modifications tabs.

**Comment by alemonteiro** [comment]
This is fixed right, can I close it?

**Comment by tanguyvda** [comment]
yes you can it is fine now :3

**Comment by alemonteiro** [comment]
thanks for the feedback =)
